
project_id = "oodpmxucntrcultdqfch"

[functions.analyze-medicine]
verify_jwt = false

[functions.analyze-reports]
verify_jwt = false

[functions.analyze-multiple-medicines]
verify_jwt = false

[functions.symptom-checker]
verify_jwt = false

[functions.ai-qa-assistant]
verify_jwt = false

[functions.ocr-prescription]
verify_jwt = false
